version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5001
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
